### ISSUE TITLE
Adding a meet up

### ISSUE THREAD

**Issue by jamieoneill** [jamieoneill/Project#8]
When adding a new meet up the maps activity is trying to read in the "Attending" field which is empty because it is added after all the other fields.
This throws a null exception. After the crash the app functions as normal the the data was added.

Fix needed: add attending into the upload with all other fields or have map class only read in after attending has been added

**Comment by david-alan-oneill** [comment]
Can you initialize the variable with a place holder each time then it is
overwritten by real value at run time

**Comment by jamieoneill** [comment]
That could work in theory. i'll check

**Comment by jamieoneill** [comment]
Fixed:
changed firebase addValueEventListener to addListenerForSingleValueEvent in maps activity

**Comment by david-alan-oneill** [comment]
Clever Java, happy days
